name: private_radio
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_serializable: ^6.8.0
  path_provider: ^2.1.3
  json_annotation: ^4.9.0
  build_runner: ^2.4.11
  image_picker: ^1.1.2
  uuid: ^4.4.0
  auto_scroll_text: ^0.0.7
  provider: ^6.1.2
  just_audio: ^0.9.38
  flutter_hooks: ^0.20.5
  audio_session: ^0.1.19

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
