name: private_radio
description: "Play audio streams like a radio. Most importantly, with NO TRACKERS and NO ADVERTS."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.1.1+4

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_serializable: ^6.8.0
  path_provider: ^2.1.3
  json_annotation: ^4.9.0
  build_runner: ^2.4.11
  image_picker: ^1.1.2
  uuid: ^4.4.0
  auto_scroll_text: ^0.0.7
  provider: ^6.1.2
  just_audio: ^0.9.38
  flutter_hooks: ^0.20.5
  audio_session: ^0.1.19
  url_launcher: ^6.3.0
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  just_audio_background: ^0.0.1-beta.12
  async: ^2.11.0
  http: ^1.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  image_path_android: "assets/images/ic_launcher.png"
  android: true

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
